### ISSUE TITLE
fix: avoid using ClientPlayNetworking.PlayChannelHandler in packet initialization

### ISSUE THREAD

**Issue by Samarium150** [Samarium150/StructuresCompass#17]
Error log provided by [moonsugarrr](https://www.curseforge.com/members/moonsugarrr/) in private messages:
```html
<html>
<body>
<!--StartFragment-->

[18:57:41] [Server thread/ERROR]: Encountered an unexpected exception
--
3 | java.lang.ExceptionInInitializerError: null
4 | at io.github.samarium150.minecraft.mod.structures_compass.network.packet.c2s.RequestSyncPacket$Companion.receive$lambda-0(RequestSyncPacket.kt:48) ~[structures_compass-fabric-1.18.2-1.4.0.jar:?]
5 | at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
6 | at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
7 | at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
8 | at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
9 | at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
10 | at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
11 | at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
12 | at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
13 | at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
14 | at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768) ~[server-intermediary.jar:?]
15 | at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[server-intermediary.jar:?]
16 | at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
17 | at java.lang.Thread.run(Thread.java:833) [?:?]
18 | Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking$PlayChannelHandler in environment type SERVER
19 | at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.13.3.jar:?]
20 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:282) ~[fabric-loader-0.13.3.jar:?]
21 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:240) ~[fabric-loader-0.13.3.jar:?]
22 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
23 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
24 | at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
25 | at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
26 | at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
27 | at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
28 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223) ~[fabric-loader-0.13.3.jar:?]
29 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) ~[fabric-loader-0.13.3.jar:?]
30 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
31 | at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
32 | at io.github.samarium150.minecraft.mod.structures_compass.network.packet.s2c.SyncPacket.<clinit>(SyncPacket.kt) ~[structures_compass-fabric-1.18.2-1.4.0.jar:?]
33 | ... 14 more

<!--EndFragment-->
</body>
</html>
```

**Comment by Samarium150** [comment]
All fabric versions are affected
