### ISSUE TITLE
GUI does not open MC 1.16.5

### ISSUE THREAD

**Issue by Lucario443** [Samarium150/StructuresCompass#7]
When I sneak and right click, nothing happens. In the console, it prints this error every time I try it.
```
[15:22:31] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
io.netty.handler.codec.EncoderException: String too big (was 44500 bytes encoded, max 32767)
	at net.minecraft.network.PacketBuffer.func_211400_a(PacketBuffer.java:532) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default}
	at net.minecraft.network.PacketBuffer.func_180714_a(PacketBuffer.java:523) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default}
	at com.github.samarium150.structurescompass.network.packet.SyncPacket.toBytes(SyncPacket.java:77) ~[structurescompass:1.16.5-1.1.0] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:134) ~[forge:?] {re:classloading}
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_231] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:132) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:147) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:85) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:forge.SimpleChannelMixin,pl:mixin:A}
	at net.minecraftforge.fml.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:98) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:forge.SimpleChannelMixin,pl:mixin:A}
	at net.minecraftforge.fml.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:129) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:forge.SimpleChannelMixin,pl:mixin:A}
	at net.minecraftforge.fml.network.simple.SimpleChannel.send(SimpleChannel.java:124) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:forge.SimpleChannelMixin,pl:mixin:A}
	at com.github.samarium150.structurescompass.network.packet.RequestSyncPacket.lambda$handle$2(RequestSyncPacket.java:49) ~[structurescompass:1.16.5-1.1.0] {re:classloading}
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?] {re:classloading}
	at com.github.samarium150.structurescompass.network.packet.RequestSyncPacket.handle(RequestSyncPacket.java:39) ~[structurescompass:1.16.5-1.1.0] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?] {re:classloading}
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_231] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:forge.SimpleChannelMixin,pl:mixin:A}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:90) ~[forge:?] {re:mixin,re:classloading}
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_231] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:90) ~[forge:?] {re:mixin,re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:191) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:153) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:169) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231] {}
```

I have about 370 mods currently loaded via MultiMC on Forge 36.1.0.
```
[1.16]compressedblocks-5.0.12.1
aas-1.16.4-1.1.0
abnormals_core-1.16.5-3.2.0
absentbydesign-1.16.5-1.5.0
acceleratorcraft-1.2.1
Actually.Useful.Smithing.Table-1.0.2.mc.1.16.3
AdvancedCompas-forge-1.16.5-1.2.1
Advanced-Firework-1.16.5-1.1
advancedtools-1.16.5-1.0.4
aimassistance-1.4.0-MC1.16.x
alchemybeta1.2
alltheores-1.3.3-1.16.5-36.1.0
allthetweaks-1.4.0-1.16.5-36.1.13
allurement-1.16.5-1.2.0
AntiArrowArea_1.16.5
antighost-1.16.4-forge35.0.7-1.1.2
anviltweaks-3.1
anystonetoolsmod_1.16.5
Apple+Cows+1.2.0
aquaticadditionsBETA1.6.1-1.16.5
architectury-1.17.22-forge
AreYouBlind-forge-1.16.x-1.1.0
Armiger-1.16.5-1.1.0
Atum-1.16.5-2.2.5
AutoDropper-1.16.3-7.0.0
automining-1.16.5-1.5
autooredictconv-1.16.4-16.1.10
autopilot-1.2
Babel-1.0.5
baritone-api-forge-1.6.2
BasaltWalker-1.16.5-1.2.2
bdlib-1.17.1.11-mc1.16.5
beaconsforall-forge-1.16.5-5.1.0.1
berry_good-1.16.5-4.1.1
betterbeaconplacement_1.16.5-1.3
BetterCommandBlock-1.0.2
BetterDiving-1.16.5-1.2.5
betterforceload-1.16.5-01
BetterMineshafts-Forge-1.16.4-2.0.4
bettersafebed-forge-1.16.5-1.4
BetterStrongholds-1.16.4-1.1
BetterThirdPerson-Forge-1.16.4-1.5.1
bettertridentreturn-1.16.4-1.0.1
bigbuckets-1.1.5
biomeborderviewer-1.16.5-8.1.0.0-forge
blame-1.16.5-3.2.3-forge
blockswap-1.1.1
Blowgun+1.16.5+-1.0
Boat-Item-View-Forge-1.16.5-0.0.2
Bookshelf-1.16.5-10.1.11
branders-spawnermod-1.16.5-1.7.11
breedingtimevisualzier-1.16.5-1.1
BridgeMaker-1.16.5-2.0.0
cabletiers-1.16x-0.24
caelus-forge-1.16.5-2.1.3.0
cant-sleep-clowns-will-eat-me-1.16.4-1.0.0.1
CapabilityProxy-1.16.5-2.1.9
carryon-1.16.5-1.15.5.15
cartographer-0.0.2-1.16.5-36.0.52
cavebiomes-2.0
CavesAndCliffsBackport-6.1
ceilingtorch-1.16.5-v1.12
cherishedworlds-forge-1.16.4-5.1.0.0
Chunk+Pregenerator-V1.16-3.0.5
citadel-1.7.1-1.16.5
cleancut-mc1.16-2.2-forge
CleanView-1.16.5-v2
ClickMachine-1.16.4-4.4.0
ClientTweaks_1.16.3-5.3.0
cloth-config-4.11.26-forge
CobbleForDays-1.3.1
cobblegenrandomizer-1.16-5.1.2
cobbler-1.6.1
CobbleToAncientDebris
cofh_core-1.16.4-1.2.1
ColdEnchants(Forge-1.16.4)vrs1.0.1
collective-1.16.5-2.26
compacter-1.4.1.5-mc1.16.5
compactores-1.16.5-3.0.3
compactstorage-1.16.5-5.1b17
compressbutton-1.2
configurablebeacons-1.16.2-2.0.1
configured-1.1.0-1.16.5
Controlling-7.0.0.23
cookiecore-1.16.2-3.0.2-9389769
corail_recycler-1.16-5.0.0
corail_woodcutter-1.16-1.3.0
corpse-1.16.5-1.0.5
CraftableSlimeBalls
CraftableTotemOfUndying-1.16.5-1.2.2
CraftingAutomat-MC1.16.3-1.2.2
CraftingCraft_1.16.3-9.2.0
CreeperHeal-1.16.5-2.0.0
curioofundying-forge-1.16.5-5.2.0.0
curios-forge-1.16.5-4.0.5.2
curiouselytra-forge-1.16.5-4.0.2.3
curiousshulkerboxes-forge-1.16.5-4.0.1.0
Cursed-1.16.5-7.0.1
customgamerules-1.16.4-1.1.1
customizableelytra-1.16.4-1.4.4
CyclopsCore-1.16.5-1.11.7
dankstorage-3.16
ddd-1.16-0.2.1
DeathFinder-v1.3-1.16.2
DeLogger-1.16.5-1.0.9+mc-1.16.5
despawningeggshatch_1.16.5-2.2
devsidetools-1.4
dimdungeons-1.12-forge-1.16.5
discerning-furnace-1.0.1
Disenchanting-forge-1.16.5-1.7.1
DisenchantmentEditTable-1.16.5-1.0.3
DoggyTalents-1.16.5-2.0.1.8
dpanvil-1.16.5-1.2.2
dragondropselytra_1.16.5-1.3
Dronecraft2_0.315
DungeonCrawl-1.16.3-2.2.4
dungeondiscs-1.5.0
dwarfcoal-1.16.4-1.0.1
DynamicTrees-1.16.5-0.10.0-Beta17
DynamicTreesPlus-1.16.5-0.1.0-Beta9
dynviewdist-2.0
easy_piglins-1.16.5-1.0.0
easy_villagers-1.16.4-1.1.28
Easy+Shulker+Access-1.16.5-1.1.1
EasyMagic-v1.0.2-1.16.5
effortlessbuilding-1.16.3-2.23
enchantedbookredesign-3.3-1.16.4
EnchantmentMachine-1.16.4-1.0.2
ender_ore-1.16.5-1.0.0
endercrop-1.16.5-1.6.0-beta
endergetic-1.16.4-3.0.0
endertap-1.1
endportalrecipe_1.16.5-2.3
enhancedcelestials-1.0.4-1.16.4
EnhancedSnowman-1.16.4-1.0.2
ensorcellation-1.16.4-1.2.0
entangled-1.3.4-mc1.16.5
EntityCulling-1.16.5-2.1.6
essentials-1.16.5-2.11.0
etched-1.1.0-1.16.5-forge
everythingscraftable_1.16.1-0.3.0
Excavator-1.8.2
Exp+Ore+Mod+-+1.16.5+-+1.3
extendedbonemeal_1.16.5-1.3
ExtraStorage-1.16.5-1.4.1
extratrades-1.16.4-1.1
FarmingForBlockheads_1.16.5-7.3.1
FasterLadderClimbing-1.16.4-0.2.1
FastLeafDecay-v25
filteredchests-1.0.2
finallyfarmabledyes-1.16.4-1.2.0.1
findme-1.16.3-2.2.0.0
fishtraps-0.1.3
flatbedrock-1.16.4-1.1.6
flickerfix-1.0.1
forgeautofish-2.1.0-1.16.x
FpsReducer-mc1.16.5-1.20
geckolib-forge-1.16.5-3.0.41
GildedIngot-1.8.9.1-1.16.5
GildingMod-FIXED
glassential-forge-1.16.5-1.1.6
God+Table+Mod+-+1.16.5
GoldenFoods
goldenhopper-1.2.0-1.16.3
grassseeds_1.16.5-1.4
GravelMiner_1.16.3-10.2.0
guifollowers_1.16.5-1.4
Haste+Enchantment+1.0.1+-+1.16.5
helpfulhitboxes-1.16.5-forge-1.0.2
horsestatsmod-MC1.16.x-1.4.2
hplus-forge-2.0.0
HydroGel-1.16.4-2.2.1
ImmersiveEngineering-1.16.5-5.0.0-135
immersive-portals-0.16-mc1.16.5-forge
industrial-foregoing-1.16.5-3.2.13.1-5
Infinite_Firework
infinitemusic-1.3.0
InfinityMending-1.16.3-0.1.0
instantunify-1.16.4-1.0.0
invautofill-1.3.3
InventoryHud_[1.16.2-1.16.5].forge-3.3.0
invtweaks-1.16.2-1.0.0
IronGenerators-1.6.0-final-1.16.x
Jade-1.16.4-2.7.1
JAOPCA-1.16.5-3.4.0.9
jei-1.16.5-7.7.0.106
jeiintegration_1.16.5-7.0.1.15
JEPB-1.0.0
jumbofurnace-1.16.4-2.2.0.1
jumpoverfences-1.16.4-1.0.1
Jungle+Villages+1.16.5++v1.1
justamagnet-1605-1.4.0-build.4
justenoughbeacons-3.1-1.16.3
JustEnoughCalculation-1.16.5-3.7.0
JustEnoughProfessions-1.16.5-1.2.1
JustEnoughResources-1.16.3-0.12.0.100
kingvillager-1.6.2
lapisreserve-1.0.7F
LavaClearView-1.16.2-1.1.0
lazydfu-0.1.3
leashed-1.2.0
lenientcreepers-1.16.2-v1.0.1
light-overlay-5.8.1
Lollipop-1.16.5-3.2.9
lowtechcrafting-1.16.3-0.2.0
lumins-0.1
Ma-Enchants-1.16.5-3.6.0
maxedvillagers-1.1
mdecore-1.16.4-16.1.0
Mekanism-1.16.5-10.0.21.448
MekanismGenerators-1.16.5-10.0.21.448
MenuFixer-1.0
minecoprocessors-1.16.5-1.0.5-b1
mineralchance_1.16.5-1.3
mining_dimension-1.16.5-1.0.5
mlgwaterbucket-1.1-1.16.4
mobcatcher-3.2
MobFarmHelpers-1.16.5-1.4.2-forge
MobileVanillaBeacons(FORGE-1.16.4)vrs1.0.1
mobtastic-1.16.5-1.0.0BETA3
mojangdark-1.16.5-1.0.2
More+Beacons-1.0.1
MoreEnchantments_MC_1.16.4_Vers.1.2.1
morevillagers-FORGE-1.16.5-1.5.1
MouseTweaks-2.14-mc1.16.2
MyBrightness-Forge-1.16.4-03
NaturesCompass-1.16.5-1.9.0
NEG-1.16.5-r1.1.1
netheritehorsearmor-1.7
netherite-plus-mod-1.4.5-1.16.5-forge
NetherPortalFix_1.16.3-7.2.1
OldCombatMod_1.16.5_v1.1
OptiFine_1.16.5_HD_U_G7
ore_reeds-1.16.3-1.1.4
Ore_Tree_v0.1.0
ore-bushes-0.5-1.16-forge
outvoted-1.16.5-1.2.4
OverpoweredMending-1.16.5-2.2.3
panoramic-1.0
paperbooks_1.16.5-1.2
performant-1.16.2-5-3.66m
Placebo-1.16.4-4.5.0
playerhopper-1.16.4-1.5
PocketDimension_1.1
pocketstorage-1.16.5-0.8.1-build.10
polymorph-forge-1.16.5-0.25
portable_stonecutter-1.16.4-1.3.4
PortableCraftingTable-1.16.5-1.1.0
portablejukebox-1.0.2
PowerCraft-Gates-1.16.3-1.1.3
proxy-0.10.0.2-mc1.16.5
quicksearchmod-MC1.16.x-1.0.1
rad-1.16-4.1.1
randomenchants-4.0.8
randomite-1.16.4-1.0.1
randomsheepcolours_1.16.5-1.4
randomshulkercolours_1.16.5-1.1
randomworldname-2.0
reap-1.16.5-1.0.0
redlogic-1.16.4-1.0.0
RedstoneExtras-1.16.2-1.0.0.8
redstonepen-1.16.5-1.0.6
refinedpipes-0.5
RefinedRelocation_1.16.5-8.2.3
refinedstorage-1.9.13
refinedstorageaddons-0.7.2
RepairChests-1.16.5-1.7
repurposed_structures-1.16.5-2.7.5-forge
ResourcefulTools-Forge-1.16.5-1.2.13
respawningshulkers_1.16.5-1.4
reusable_rockets-1.16.5-1.0.1
RevampedWolf-1.16.4-0.7.1
RingOfEnderchest-Forge-1.16.5-1.2.8
RingOfRepair-Forge-1.16.5-1.2.14
Rotzp-1.16.5_1.0.0
scaffoldingdropsnearby_1.16.5-1.3
ScalableCatsForce-2.13.5-build-2-with-library
Scannable-MC1.16.5-1.7.3.17
SCBbeta1.1.0
scuba-gear-1.16.5-1.0.3
seamless_loading_screen-1.16.5-1.1.6
searchablechests-1.16-1.5.4
Shrines-1.16.5-1.8.1
shulker_enchantments-1.1.1
shulkerbox-1.16.5-1.0.0
shulkerdropstwo_1.16.5-1.4
ShulkerTooltip-1.9.8
shutupexperimentalsettings-1.0.3
SignButton-1.16.3-2.1.3
simplegens-1.16.5-3.0.8.0
skeletonhorsespawn_1.16.5-1.6
sleeping_bags-1.16.5-1.0.1
sleepsooner_1.16.5-2.4
slime_ore-0.1
slimedetector-1.1
SlimeGolems-1.16.5_01
SlimyChunks(1.16.4)-1.0.4
Slip-forge-1.16.4
smallernetherportals_1.16.5-1.6
SneakyMagic-v1.3.2-1.16.5
solarcooker-0.4.0-1.16.1+
SolarFluxReborn-1.16.3-16.2.5
sounddeviceoptions-1.4.2
SoundFilters-0.14_for_1.16.2
spatialharvesters_forge_1.16.5-0.11.10
SpawnerFix-1.16.2-1.0.0.1
speedyhoppers-1.16.4-1
spiders-2.0-1.16.4-1.0.4
sssrebornmod_1.16.5_v1.0.0
step-1.16.4-1.1.0
stoneholm-1.2.2
strawgolem-1.16-1.9
structure_gel-1.16.5-1.7.7
structurescompass-1.16.5-1.1.0
subpocket-1.16-6.0.0.2
SuggestionProviderFix-1.16.5-1.0.0
supermartijn642configlib-1.0.8-mc1.16
supermartijn642corelib-1.0.9-mc1.16.5
TbscClick-MC1.16.4-v2.2.0
The_Undergarden-1.16.5-0.5.4
The-Cactus-Mod-1.16.5-1.3.5.1
TheFletchingTableMod_1.16.5_v1.2
theplopper-1.16.2-v1.3.1
thermal_expansion-1.16.4-1.2.0
thermal_foundation-1.16.4-1.2.0
TinyMobFarm-1.16.3-1.1.1
titanium-1.16.5-3.2.8.4-10
toms_storage-1.2.16
TonsOfEnchants-0.6v
tonsoftotemsv1.4.2
too_hard_for_me+-1.1.0
toolleveling-1.16.5-1.2.3
ToolSwap-1.16.2-1.3.1
torcherino-13.0.3+1.16.3
torch-key-forge-0.2
torchslabmod-1.16.4_v1.6.19
toughnessbar-6.1
TrampleStopper-2.4.9+mc-1.16.5
Trapcraft-1.16.5-3.3.0
Tropicraft-9.0.0-beta+54
tubesreloaded-1.16.5-1.5.0.3
twilightforest-1.16.5-4.0.490-universal
twuhastepotion-1.0
Undestroying-1.16.5-1.2.0
Unique+Enchantments+Battle-1.16.5-1.0
Unique+Enchantments-1.16.5-2.0.1
Upgraded+Netherite+1.16.5+-+1.9.5
Uppers-0.3.2
upsizer-mc1.16.4-6.1.1
valhelsia_core-16.0.9
valhelsia_structures-1.16.5-0.1.2
valkyrielib-1.16.5-3.0.9.0
Villager+Yeeter-1.16.5-0.2
villagernames_1.16.5-2.9
VillagersRespawn-1.16.5-1.36.0.4
villagertools-1.16.5-1.0.0
villainousdifficultymultipliers-1.3.1
visiblearmorslots-2.0-1.16.5
VS+8.0.0
WaterStrainer-1.16.3-10.0.0
withereggs-1.16.5-1.2
WithoutALib-1.16.5-0.1.4
WithoutARedstone-1.16.5-1.0.2
woodenhopper-1.1.0-1.16.2+
WoolyTrees-1.16.5-1.0.1
woot-1.16.5-1.0.7.0
WorldHandler-1.16.5-2.12.5
YungsApi-1.16.4-Forge-6
zombievillagersfromspawner_1.16.5-1.4
```
I've also attached the whole log from starting minecraft up until trying using the compass a few times.
[latest.log](https://github.com/Samarium150/StructuresCompass/files/6760487/latest.log)

**Comment by Samarium150** [comment]
Thanks for your report. It's caused by too many structures generated by your mods. We'll try to fix it, and for now, a quick workaround is reducing the number of your mods.

**Comment by Lucario443** [comment]
Thanks. I'll keep a look out for updates and reevaluate my mod count.
